# Generated by Django 4.0.1 on 2022-07-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SitePage',
            new_name='About',
        ),
    ]
