# Generated by Django 4.0.1 on 2022-07-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_ourpeople_center_for_christianity_and_scholarship_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourpeople',
            old_name='center_for_christianity_and_scholarship_staff',
            new_name='CCS_staff',
        ),
    ]
