# Generated by Django 4.0.1 on 2022-07-19 08:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_ourpeople_ccs_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpeople',
            name='CCS_house_staff',
            field=wagtail.fields.StreamField([('staff_member', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('headshot', wagtail.images.blocks.ImageChooserBlock(required=False)), ('year', wagtail.blocks.CharBlock()), ('major', wagtail.blocks.CharBlock())]))], default='', use_json_field=None),
            preserve_default=False,
        ),
    ]
