# Generated by Django 4.0.1 on 2022-07-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_ourpeople_ccs_house_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourpeople',
            name='body',
        ),
    ]
