# Generated by Django 4.0.1 on 2022-07-19 08:40

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_ourpeople_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpeople',
            name='CCS_house_staff',
            field=wagtail.fields.StreamField([('student_staffer', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('headshot', wagtail.images.blocks.ImageChooserBlock(required=False)), ('year', wagtail.blocks.CharBlock()), ('major', wagtail.blocks.CharBlock())]))], use_json_field=None),
        ),
    ]
