# Generated by Django 4.0.1 on 2022-07-19 16:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_ourpeople_ccs_house_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpeople',
            name='CCS_staff',
            field=wagtail.fields.StreamField([('staff_member', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('position', wagtail.blocks.CharBlock()), ('headshot', wagtail.images.blocks.ImageChooserBlock(required=False)), ('biography', wagtail.blocks.RichTextBlock())]))], use_json_field=None),
        ),
    ]
