# Generated by Django 4.0.1 on 2022-07-19 16:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_ourpeople_ccs_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpeople',
            name='CCS_faculty_affiliates',
            field=wagtail.fields.StreamField([('student_staffer', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('headshot', wagtail.images.blocks.ImageChooserBlock(required=False))]))], default='', use_json_field=None),
            preserve_default=False,
        ),
    ]
