# Generated by Django 4.0.1 on 2022-08-01 16:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_ourpeople_ccs_faculty_affiliates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourpeople',
            name='CCS_house_staff',
        ),
        migrations.AlterField(
            model_name='ourpeople',
            name='CCS_faculty_affiliates',
            field=wagtail.fields.StreamField([('faculaty_affiliate', wagtail.blocks.StructBlock([('first_name', wagtail.blocks.CharBlock()), ('last_name', wagtail.blocks.CharBlock()), ('headshot', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, use_json_field=None),
        ),
    ]
