# Generated by Django 4.0.1 on 2022-08-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_ourpeople_ccs_house_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourpeople',
            name='CCS_faculty_affiliates',
        ),
    ]
