# Generated by Django 4.0.1 on 2022-07-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
