# Generated by Django 4.0.8 on 2023-01-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_ourfaculty_ourstaff_whatwedo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatWeDo',
        ),
    ]
