# Generated by Django 4.0.1 on 2022-07-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_samplepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SamplePage',
        ),
    ]
