# Generated by Django 4.0.8 on 2023-01-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0006_certificationpathway_currentevents_donate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurStaff',
            new_name='OurStaffIndex',
        ),
    ]
