# Generated by Django 4.0.8 on 2023-01-14 12:38

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ourstaffentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstaffentry',
            name='name',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
