# Generated by Django 4.0.8 on 2023-01-14 13:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0011_ourstaffentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcoursesentry',
            name='description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcoursesentry',
            name='instructor',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcoursesentry',
            name='location',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcoursesentry',
            name='meeting_schedule',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcoursesentry',
            name='name',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcoursesentry',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='shortcoursesentry',
            name='registration_link',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourstaffentry',
            name='type',
            field=wagtail.fields.RichTextField(choices=[('staff', 'Staff'), ('boardOfDirectors', 'Board of Directors'), ('advisoryCouncil', 'Faculty Advisory Council')]),
        ),
    ]
