# Generated by Django 4.0.8 on 2023-01-18 03:28

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_homepage_body_homepage_offerings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='houseSlides',
            field=wagtail.fields.StreamField([('photo', wagtail.images.blocks.ImageChooserBlock(required=True))], blank=True, null=True, use_json_field=True),
        ),
    ]
