# Generated by Django 4.0.8 on 2023-01-18 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0015_homepage_houseslides'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_2_feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
