# Generated by Django 4.0.8 on 2023-01-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0017_homepage_banner_3_feature_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='WhoWeAre',
        ),
    ]
