# Generated by Django 4.0.8 on 2023-01-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0018_rename_about_whoweare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='Give',
        ),
    ]
