# Generated by Django 4.0.8 on 2023-01-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0022_remove_evententry_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventEntry',
            new_name='Event',
        ),
    ]
