# Generated by Django 4.0.8 on 2023-01-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0024_eventinstance_remove_event_date_remove_event_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortCoursesIndex',
            new_name='CoursesIndex',
        ),
    ]
