# Generated by Django 4.0.8 on 2023-01-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_shortcoursesindex_coursesindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcoursesentry',
            name='meeting_schedule',
        ),
    ]
