# Generated by Django 4.0.8 on 2023-01-20 01:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_shortcoursesentry_meeting_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcoursesentry',
            name='type',
            field=wagtail.fields.RichTextField(blank=True, choices=[('readingGroup', 'Reading Group'), ('shortCourse', 'Short Course')], null=True),
        ),
    ]
