# Generated by Django 4.0.8 on 2023-01-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_shortcoursesentry_courseentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseentry',
            name='name',
        ),
    ]
