# Generated by Django 4.0.8 on 2023-01-20 01:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_courseentry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentry',
            name='type',
            field=wagtail.fields.RichTextField(blank=True, choices=[('Reading Group', 'Reading Group'), ('Short Course', 'Short Course')], null=True),
        ),
    ]
