# Generated by Django 4.0.8 on 2023-01-20 16:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_courseentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='what_we_do',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.CharBlock())]))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
