# Generated by Django 4.0.8 on 2023-01-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_homepage_what_we_offer_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='what_we_offer_heading',
            field=models.CharField(max_length=255),
        ),
    ]
