# Generated by Django 4.0.8 on 2023-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_homepage_what_we_offer_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='what_we_do_header',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_we_offer_footer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
