# Generated by Django 4.0.8 on 2023-01-20 16:15

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_homepage_what_we_do_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='map_button_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_button_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_description_text',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_title_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
