# Generated by Django 4.0.8 on 2023-01-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_homepage_map_button_link_homepage_map_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slides_header_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
