# Generated by Django 4.0.8 on 2023-01-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_homepage_slides_header_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_3_feature_image',
            new_name='what_we_do_feature_image',
        ),
    ]
