# Generated by Django 4.0.8 on 2023-01-20 16:21

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_banner_2_feature_image_homepage_what_we_believe_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='we_believe_button_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='we_believe_button_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='we_believe_description_text',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='we_believe_title_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
