# Generated by Django 4.0.8 on 2023-01-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_homepage_we_believe_button_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='what_we_believe_feature_image',
            new_name='we_believe_feature_image',
        ),
    ]
