# Generated by Django 4.0.8 on 2023-01-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_rename_what_we_believe_feature_image_homepage_we_believe_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_button_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_button_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
