# Generated by Django 4.0.8 on 2023-01-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_homepage_banner_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='what_we_offer_footer',
        ),
    ]
