# Generated by Django 4.0.8 on 2023-01-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_homepage_what_we_offer_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentry',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courseentry',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='courseentry',
            name='registration_link',
            field=models.CharField(max_length=255),
        ),
    ]
