# Generated by Django 4.0.8 on 2023-01-20 17:14

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_courseentry_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentry',
            name='instructor',
            field=wagtail.fields.RichTextField(),
        ),
    ]
