# Generated by Django 4.0.8 on 2023-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_courseentry_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseentry',
            name='meeting_pattern',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
    ]
