# Generated by Django 4.0.8 on 2023-01-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0052_conference_conferenceindex_lecture_lectureindex_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurStaffEntry',
            new_name='LeadershipEntry',
        ),
    ]
