# Generated by Django 4.0.8 on 2023-01-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0053_rename_ourstaffentry_leadershipentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurFaculty',
            new_name='FacultyAffiliatesIndex',
        ),
    ]
