# Generated by Django 4.0.8 on 2023-01-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_delete_mentorshipopportunities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradStudents',
        ),
    ]
