# Generated by Django 4.0.8 on 2023-02-08 18:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_facultyreadinggroupentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendahand',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock())], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
