# Generated by Django 4.0.8 on 2023-02-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_facultyaffiliatesentry_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyaffiliatesentry',
            name='website',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
    ]
