# Generated by Django 4.0.8 on 2023-02-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_facultyaffiliatesentry_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyaffiliatesentry',
            name='name',
        ),
        migrations.AddField(
            model_name='facultyaffiliatesentry',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyaffiliatesentry',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
