# Generated by Django 4.0.8 on 2023-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_readinggroupsindex_descriptive_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseentry',
            name='semester',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='semester',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
