# Generated by Django 4.0.8 on 2023-02-28 15:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_whoweare_beliefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoweare',
            name='beliefs',
            field=wagtail.fields.StreamField([('belief', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock())]))], use_json_field=True),
        ),
    ]
