# Generated by Django 4.0.8 on 2023-03-06 14:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_alter_whoweare_beliefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesindex',
            name='type',
            field=wagtail.fields.RichTextField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active'),
            preserve_default=False,
        ),
    ]
