# Generated by Django 4.0.8 on 2023-03-06 16:18

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_alter_courseentry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='type',
            field=wagtail.fields.RichTextField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active'),
            preserve_default=False,
        ),
    ]
