# Generated by Django 4.0.8 on 2023-03-07 02:09

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_alter_courseentry_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='instructor',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='location',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='meeting_pattern',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='registration_link',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='semester',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
