# Generated by Django 4.0.8 on 2023-03-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alter_readinggroup_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificationPathway',
        ),
        migrations.DeleteModel(
            name='FellowsProgram',
        ),
        migrations.DeleteModel(
            name='FormationGroup',
        ),
        migrations.DeleteModel(
            name='IncomingStudents',
        ),
    ]
