# Generated by Django 4.0.8 on 2023-03-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_remove_fellowsprogram_page_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduatechristianscholars',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ChristianScholarshipWorkshop',
        ),
        migrations.DeleteModel(
            name='GraduateChristianScholars',
        ),
    ]
