# Generated by Django 4.0.8 on 2023-03-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_remove_graduatechristianscholars_page_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyreadinggroups',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='scholarshipworkshop',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='triangleroundtable',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FacultyReadingGroupEntry',
        ),
        migrations.DeleteModel(
            name='FacultyReadingGroups',
        ),
        migrations.DeleteModel(
            name='ScholarshipWorkshop',
        ),
        migrations.DeleteModel(
            name='TriangleRoundtable',
        ),
    ]
