# Generated by Django 4.0.8 on 2023-03-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
