# Generated by Django 4.0.8 on 2023-04-05 13:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_house_east_campus_map_house_map_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipindex',
            name='leadership_description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
