# Generated by Django 4.0.8 on 2023-04-11 13:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_house_house_programming_house_programming_title_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_programming',
            field=wagtail.fields.StreamField([('program', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('button_text', wagtail.blocks.CharBlock()), ('button_reference', wagtail.blocks.CharBlock()), ('feature_image', wagtail.images.blocks.ImageChooserBlock())]))], use_json_field=True),
        ),
    ]
