# Generated by Django 4.0.8 on 2023-04-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_eventindex_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventIndex',
        ),
    ]
