# Generated by Django 4.0.8 on 2023-04-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0102_event_location_event_poster_event_registration_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurriculumPage',
            new_name='CertificatePathwayPage',
        ),
    ]
