# Generated by Django 4.0.8 on 2023-04-20 14:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0103_rename_curriculumpage_certificatepathwaypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='contact_button_link',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='contact_button_text',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='contact_description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='contact_headshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='course_block_button_link',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='course_block_button_text',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='course_block_description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='course_block_header_1',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='course_block_header_2',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='eligable_courses',
            field=wagtail.fields.StreamField([('content_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.CharBlock())]))], default='', use_json_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='eligable_projects',
            field=wagtail.fields.StreamField([('content_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.CharBlock())]))], default='', use_json_field=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='page_description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='project_block_button_link',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='project_block_button_text',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='project_block_description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='project_block_header_1',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatepathwaypage',
            name='project_block_header_2',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
