# Generated by Django 4.0.8 on 2023-04-20 15:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_certificatepathwaypage_contact_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatepathwaypage',
            name='eligable_courses',
            field=wagtail.fields.StreamField([('content_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock(blank=True)), ('button_link', wagtail.blocks.CharBlock(blank=True))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='certificatepathwaypage',
            name='eligable_projects',
            field=wagtail.fields.StreamField([('content_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock(blank=True)), ('button_link', wagtail.blocks.CharBlock(blank=True))]))], use_json_field=True),
        ),
    ]
