# Generated by Django 4.0.8 on 2023-04-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_fellowsprogramindex_summerprogramsindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Give',
        ),
    ]
