# Generated by Django 4.0.8 on 2023-04-20 22:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_delete_give'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseentry',
            name='category',
            field=wagtail.fields.RichTextField(choices=[('house_course', 'House Course'), ('duke_course', 'Duke Course')], default=''),
            preserve_default=False,
        ),
    ]
