# Generated by Django 4.0.8 on 2023-04-20 23:03

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_courseentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentry',
            name='category',
            field=wagtail.fields.RichTextField(choices=[('House Course', 'House Course'), ('Duke Course', 'Duke Course')]),
        ),
    ]
