# Generated by Django 4.0.8 on 2023-04-24 16:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_archivepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepage',
            name='archived_items',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('date', wagtail.blocks.DateBlock(required=False)), ('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], use_json_field=True),
        ),
    ]
