# Generated by Django 4.0.8 on 2023-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_programpage_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='archived_programs_header',
            field=models.CharField(default='', max_length=511),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programpage',
            name='current_programs_header',
            field=models.CharField(default='', max_length=511),
            preserve_default=False,
        ),
    ]
