# Generated by Django 4.0.8 on 2023-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_onetimeprogram_recurringprogram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeprogram',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='onetimeprogram',
            name='meeting_pattern',
        ),
        migrations.RemoveField(
            model_name='onetimeprogram',
            name='semester',
        ),
        migrations.AddField(
            model_name='onetimeprogram',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onetimeprogram',
            name='presenter',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AddField(
            model_name='onetimeprogram',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
