# Generated by Django 4.0.8 on 2023-04-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_remove_onetimeprogram_instructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimeprogram',
            old_name='registration_link',
            new_name='link',
        ),
    ]
