# Generated by Django 4.0.8 on 2023-04-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0119_rename_registration_link_onetimeprogram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeprogram',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='onetimeprogram',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='feature_image',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='recurringprogram',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='recurringprogram',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='recurringprograminstance',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ArchivePage',
        ),
        migrations.DeleteModel(
            name='OneTimeProgram',
        ),
        migrations.DeleteModel(
            name='ProgramPage',
        ),
        migrations.DeleteModel(
            name='RecurringProgram',
        ),
        migrations.DeleteModel(
            name='RecurringProgramInstance',
        ),
    ]
