# Generated by Django 4.0.8 on 2023-04-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0120_remove_onetimeprogram_page_ptr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseEntry',
            new_name='Course',
        ),
    ]
