# Generated by Django 4.0.8 on 2023-04-24 18:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0121_rename_courseentry_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='archival_link',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='location',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AddField(
            model_name='lecture',
            name='registration_link',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='type',
            field=wagtail.fields.RichTextField(choices=[('active', 'Active'), ('archived', 'Archived')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureindex',
            name='descriptive_text',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureindex',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='lectureindex',
            name='header_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
