# Generated by Django 4.0.8 on 2023-04-24 19:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_lecture_archival_link_lecture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatepathwaypage',
            name='eligable_courses',
            field=wagtail.fields.StreamField([('content_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('semester', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('button_text', wagtail.blocks.CharBlock(blank=True, required=False)), ('button_link', wagtail.blocks.CharBlock(blank=True, required=False))]))], use_json_field=True),
        ),
    ]
