# Generated by Django 4.0.8 on 2023-04-24 19:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_alter_certificatepathwaypage_eligable_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=wagtail.fields.RichTextField(choices=[('future', 'Future'), ('active', 'Active'), ('archived', 'Archived')]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=wagtail.fields.RichTextField(choices=[('future', 'Future'), ('active', 'Active'), ('archived', 'Archived')]),
        ),
        migrations.AlterField(
            model_name='readinggroup',
            name='type',
            field=wagtail.fields.RichTextField(choices=[('future', 'Future'), ('active', 'Active'), ('archived', 'Archived')]),
        ),
    ]
