# Generated by Django 4.0.8 on 2023-04-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0126_globaldata_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalData',
        ),
    ]
