# Generated by Django 4.0.8 on 2023-04-24 22:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0128_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='message',
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_links',
            field=wagtail.fields.StreamField([('category', wagtail.blocks.StructBlock([('category_name', wagtail.blocks.CharBlock()), ('cateogry_links', wagtail.blocks.StreamBlock([('link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock()), ('link_reference', wagtail.blocks.CharBlock())]))]))]))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
