# Generated by Django 4.0.8 on 2023-04-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0135_footer_house_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='email_address',
        ),
    ]
