# Generated by Django 4.0.8 on 2023-04-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0137_footer_email_address_footer_mailto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='ccs_house_header_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='footer',
            name='ccs_house_header_text',
            field=models.CharField(default='', max_length=511),
            preserve_default=False,
        ),
    ]
