# Generated by Django 4.0.8 on 2023-04-24 23:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0138_footer_ccs_house_header_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation', wagtail.fields.StreamField([('category', wagtail.blocks.StructBlock([('category_name', wagtail.blocks.CharBlock()), ('category_links', wagtail.blocks.StreamBlock([('internal_link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock()), ('link_reference', wagtail.blocks.PageChooserBlock())])), ('external_link', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock()), ('link_reference', wagtail.blocks.CharBlock())]))]))])), ('internal_button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.PageChooserBlock())])), ('external_button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_link', wagtail.blocks.CharBlock())]))], use_json_field=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
