# Generated by Django 4.0.8 on 2023-04-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0140_rename_event_recurringevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventInstance',
            new_name='RecurringEventInstance',
        ),
    ]
