# Generated by Django 4.0.8 on 2023-04-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0142_onetimeevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringEvent',
            new_name='Event',
        ),
    ]
