# Generated by Django 4.0.8 on 2023-04-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0143_rename_recurringevent_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeEvent',
        ),
    ]
