# Generated by Django 4.0.8 on 2023-04-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0144_delete_onetimeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='associated_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='event',
            name='leader',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.DeleteModel(
            name='RecurringEventInstance',
        ),
    ]
