# Generated by Django 4.0.8 on 2023-04-26 14:44

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0145_event_associated_page_event_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meetings',
            field=wagtail.fields.StreamField([('meeting', wagtail.blocks.StructBlock([('date_and_time', wagtail.blocks.DateTimeBlock()), ('place', wagtail.blocks.CharBlock(default=models.CharField(blank=True, max_length=1023)))]))], default='', use_json_field=None),
            preserve_default=False,
        ),
    ]
