# Generated by Django 4.0.8 on 2023-04-26 14:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0147_alter_event_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meetings',
            field=wagtail.fields.StreamField([('meeting', wagtail.blocks.StructBlock([('date', wagtail.blocks.DateBlock()), ('time', wagtail.blocks.TimeBlock()), ('place', wagtail.blocks.CharBlock(help_text="Leave blank to use the event's default location.", required=False))]))], use_json_field=None),
        ),
    ]
