# Generated by Django 4.0.8 on 2023-04-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0154_alter_event_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='associated_page',
            field=models.ForeignKey(blank=True, help_text='Leave blank to associate this event with an automatically generated page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
