# Generated by Django 4.0.8 on 2023-04-26 19:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0155_alter_event_associated_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meetings',
            field=wagtail.fields.StreamField([('meeting', wagtail.blocks.StructBlock([('date', wagtail.blocks.DateBlock()), ('start_time', wagtail.blocks.TimeBlock()), ('place', wagtail.blocks.CharBlock(help_text="Leave blank to use the event's default location.", required=False)), ('description', wagtail.blocks.RichTextBlock(help_text="Optional description of the meeting (e.g. the content covered in a course or reading group session, special instructions for a particular meeting, etc). Leave blank to use the event's default description.", required=False))]))], use_json_field=None),
        ),
    ]
