# Generated by Django 4.0.8 on 2023-05-22 17:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0158_alter_leadershipentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipindex',
            name='display_staff',
            field=wagtail.fields.StreamField([('staff_member', wagtail.blocks.PageChooserBlock(page_type=['home.LeadershipEntry']))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
