# Generated by Django 4.0.8 on 2023-05-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0159_leadershipindex_display_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadershipindex',
            old_name='display_staff',
            new_name='staff_members_displayed',
        ),
    ]
