# Generated by Django 4.0.8 on 2023-05-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0160_rename_display_staff_leadershipindex_staff_members_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipentry',
            name='last_name',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
