# Generated by Django 4.0.8 on 2023-05-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0161_leadershipentry_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadershipentry',
            old_name='name',
            new_name='first_name',
        ),
    ]
