# Generated by Django 4.0.8 on 2023-05-22 17:55

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0163_coursesindex_active_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=wagtail.fields.RichTextField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')]),
        ),
    ]
