# Generated by Django 4.0.8 on 2023-05-22 18:32

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0166_alter_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='suborder_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=wagtail.fields.RichTextField(choices=[('1_spring', 'Spring'), ('2_summer', 'Summer'), ('3_fall', 'Fall')]),
        ),
    ]
