# Generated by Django 4.0.8 on 2023-05-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0167_course_suborder_index_alter_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='suborder_index',
        ),
    ]
