# Generated by Django 4.0.8 on 2023-05-22 18:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0168_remove_course_suborder_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='semester',
            field=wagtail.fields.RichTextField(choices=[('1_spring', 'Spring'), ('2_summer', 'Summer'), ('3_fall', 'Fall')]),
        ),
    ]
