# Generated by Django 4.0.8 on 2023-06-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0171_house_house_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_programming',
        ),
        migrations.RemoveField(
            model_name='house',
            name='programming_title_text',
        ),
    ]
