# Generated by Django 4.0.8 on 2023-06-29 02:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0176_alter_custompage_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='page_content',
            field=wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('background_color', wagtail.blocks.ChoiceBlock(choices=[('rose', 'Rose'), ('navy', 'Navy'), ('white', 'White'), ('burgundy', 'Burgundy')])), ('article_content', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_reference', wagtail.blocks.CharBlock())]))]))])), ('text_and_image_full_section', wagtail.blocks.StructBlock([('background_color', wagtail.blocks.ChoiceBlock(choices=[('rose', 'Rose'), ('navy', 'Navy'), ('white', 'White'), ('burgundy', 'Burgundy')])), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('side_by_side', 'Side by Side'), ('card', 'Card')])), ('text_side_content', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_reference', wagtail.blocks.CharBlock())]))], use_json_field=True)), ('featured_image', wagtail.images.blocks.ImageChooserBlock())])), ('card_collection_section', wagtail.blocks.StructBlock([('background_color', wagtail.blocks.ChoiceBlock(choices=[('rose', 'Rose'), ('navy', 'Navy'), ('white', 'White'), ('burgundy', 'Burgundy')])), ('title', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.StreamBlock([('image_card', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('text_card', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_reference', wagtail.blocks.CharBlock())]))], use_json_field=True))]))], use_json_field=True))]))], use_json_field=True),
        ),
    ]
