# Generated by Django 4.0.8 on 2023-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0187_alter_custompage_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipindex',
            name='advisory_board_header',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadershipindex',
            name='board_of_directors_header',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadershipindex',
            name='staff_header',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
