# Generated by Django 4.0.8 on 2023-06-30 01:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0193_alter_custompage_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='give_description',
        ),
        migrations.AddField(
            model_name='give',
            name='donation_hero_text',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give',
            name='donation_widget_description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give',
            name='donation_widget_heading',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='give',
            name='giving_options_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='give',
            name='more_options_header',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
