# Generated by Django 4.0.8 on 2023-06-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0194_remove_give_give_description_give_donation_hero_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Give',
        ),
    ]
