# Generated by Django 4.0.8 on 2023-06-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0196_give'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Give',
        ),
    ]
