# Generated by Django 4.0.8 on 2023-06-30 02:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0200_remove_give_footer_links_give_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='testimonials_bhahhhh',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock()), ('button_reference', wagtail.blocks.CharBlock())]))], use_json_field=True))]))], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
