# Generated by Django 4.0.8 on 2023-06-30 02:41

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0203_alter_give_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='give',
            name='blah',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
