# Generated by Django 4.0.8 on 2023-06-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0204_give_blah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='give',
            name='more_options_header',
        ),
    ]
