# Generated by Django 4.0.8 on 2023-06-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0205_remove_give_more_options_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='give',
            old_name='blah',
            new_name='more_options_header',
        ),
    ]
