# Generated by Django 4.0.8 on 2023-07-04 17:33

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0206_rename_blah_give_more_options_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='header_color',
            field=wagtail.fields.RichTextField(choices=[('navy', 'Navy'), ('white', 'White')], default=''),
            preserve_default=False,
        ),
    ]
