# Generated by Django 4.0.8 on 2023-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0209_alter_custompage_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
