# Generated by Django 4.0.8 on 2023-07-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0210_lecture_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='archival_link',
        ),
    ]
