# Generated by Django 4.0.8 on 2023-07-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0212_lecture_video_embed_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video_embed_link',
        ),
    ]
