# Generated by Django 4.0.8 on 2023-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0213_remove_lecture_video_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_embed_link',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
