# Generated by Django 4.0.8 on 2023-07-04 20:00

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0214_lecture_video_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=wagtail.fields.RichTextField(choices=[('Short Course', 'Short Course'), ('House Course', 'House Course')]),
        ),
    ]
