# Generated by Django 4.0.8 on 2023-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0217_remove_lecture_date_remove_lecture_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
