# Generated by Django 4.0.8 on 2023-07-05 01:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0222_lectureindex_active_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='for_faculty',
            field=wagtail.fields.RichTextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='for_friends',
            field=wagtail.fields.RichTextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='for_grad_students',
            field=wagtail.fields.RichTextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='for_undergrads',
            field=wagtail.fields.RichTextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
            preserve_default=False,
        ),
    ]
