# Generated by Django 4.0.8 on 2023-07-05 20:07

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0223_event_for_faculty_event_for_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureindex',
            name='display_archive',
            field=wagtail.fields.RichTextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
            preserve_default=False,
        ),
    ]
