# Generated by Django 4.0.8 on 2023-07-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0226_alter_footer_social_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='mailing_list_button_link',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='mailing_list_button_text',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
